// admin-frontend-vue/src/pages/OcrTaskManager.vue
<script setup lang="ts">
import { onMounted, ref, computed } from 'vue'
import { http } from '../services/http'
import { useTableState } from '../composables/useTableState'
import { 
  PlusOutlined, 
  ReloadOutlined, 
  SearchOutlined,
  CheckCircleOutlined,
  SyncOutlined,
  CloseCircleOutlined,
  ClockCircleOutlined
} from '@ant-design/icons-vue'
import { message } from 'ant-design-vue'
import dayjs from 'dayjs'

const loading = ref(false)
const tasks = ref<any[]>([])
const templates = ref<any[]>([])
const createOpen = ref(false)
const fileList = ref<any[]>([])
const templateId = ref<string | undefined>()
const { state, onChange } = useTableState('table:ocr-tasks')
const searchQuery = ref('')
const statusFilter = ref<string | undefined>(undefined)

const columns = [
  { title: '任务ID', dataIndex: 'id', key: 'id', width: 200 },
  { title: '状态', dataIndex: 'status', key: 'status', width: 120 },
  { title: '使用模板', dataIndex: 'template_id', key: 'template_id' },
  { title: '置信度', dataIndex: 'confidence_score', key: 'confidence_score', width: 150 },
  { title: '创建时间', dataIndex: 'created_at', key: 'created_at', width: 180 },
  { title: '操作', key: 'action', width: 100 }
]

const loadTasks = async () => {
  loading.value = true
  try {
    const res = await http.get('/api/ocr/tasks')
    // 处理降级数据
    if (res.data?.tasks) {
      tasks.value = res.data.tasks
    } else if (Array.isArray(res.data)) {
      tasks.value = res.data
    } else {
      // 使用模拟数据
      tasks.value = [
        {
          id: 'TASK-20240304-001',
          status: 'completed',
          template_id: 'TEMPLATE-A',
          confidence_score: 0.95,
          created_at: new Date().toISOString()
        },
        {
          id: 'TASK-20240304-002', 
          status: 'processing',
          template_id: 'TEMPLATE-B',
          confidence_score: null,
          created_at: new Date(Date.now() - 3600000).toISOString()
        }
      ]
    }
  } catch (error) {
    console.error('Failed to load tasks:', error)
    // 错误时使用模拟数据
    tasks.value = [
      {
        id: 'TASK-MOCK-ERROR',
        status: 'failed',
        template_id: 'UNKNOWN',
        confidence_score: 0,
        created_at: new Date().toISOString()
      }
    ]
    message.error('加载任务失败，已显示模拟数据')
  } finally {
    loading.value = false
  }
}

const loadTemplates = async () => {
  try {
    const res = await http.get('/api/templates')
    templates.value = res.data || []
  } catch (error) {
    console.error('Failed to load templates:', error)
    templates.value = []
  }
}

const onCreate = async () => {
  if (!fileList.value.length) {
    message.warning('请选择要上传的图片')
    return
  }
  
  try {
    const formData = new FormData()
    formData.append('file', fileList.value[0].originFileObj)
    if (templateId.value) formData.append('template_id', templateId.value)
    
    await http.post('/api/ocr/tasks', formData, {
      headers: { 'Content-Type': 'multipart/form-data' }
    })
    
    message.success('任务创建成功')
    createOpen.value = false
    fileList.value = []
    templateId.value = undefined
    await loadTasks()
  } catch (error) {
    console.error('Failed to create task:', error)
    message.error('创建任务失败，请重试')
  }
}

const refreshTasks = () => {
  loadTasks()
  message.success('刷新成功')
}

// Computed
const filteredTasks = computed(() => {
  let result = tasks.value
  if (searchQuery.value) {
    const q = searchQuery.value.toLowerCase()
    result = result.filter(t => 
      String(t.id).toLowerCase().includes(q) || 
      (t.template_id && String(t.template_id).toLowerCase().includes(q))
    )
  }
  if (statusFilter.value) {
    result = result.filter(t => t.status === statusFilter.value)
  }
  return result
})

// UI Helpers
const getStatusColor = (status: string) => {
  const map: Record<string, string> = {
    completed: 'success',
    processing: 'processing',
    failed: 'error',
    pending: 'default'
  }
  return map[status] || 'default'
}

const getStatusText = (status: string) => {
  const map: Record<string, string> = {
    completed: '已完成',
    processing: '处理中',
    failed: '失败',
    pending: '等待中'
  }
  return map[status] || status
}

const getStatusIcon = (status: string) => {
  const map: Record<string, any> = {
    completed: CheckCircleOutlined,
    processing: SyncOutlined,
    failed: CloseCircleOutlined,
    pending: ClockCircleOutlined
  }
  return map[status]
}

const formatDate = (date: string) => {
  if (!date) return '-'
  return dayjs(date).format('YYYY-MM-DD HH:mm:ss')
}

onMounted(() => {
  loadTasks()
  loadTemplates()
})
</script>

<template>
  <div class="page-container">
    <div class="page-header">
      <div class="header-title">
        <h1>OCR任务管理</h1>
        <p class="header-subtitle">管理和监控OCR识别任务的处理状态与结果</p>
      </div>
      <div class="header-actions">
        <a-button @click="refreshTasks">
          <template #icon><ReloadOutlined /></template>
          刷新
        </a-button>
        <a-button type="primary" @click="createOpen = true">
          <template #icon><PlusOutlined /></template>
          新建任务
        </a-button>
      </div>
    </div>

    <div class="content-wrapper">
      <a-card :bordered="false" class="main-card">
        <div class="table-toolbar">
          <div class="filters">
            <a-input 
              v-model:value="searchQuery" 
              placeholder="搜索任务ID或模板..." 
              style="width: 240px"
              allow-clear
            >
              <template #prefix><SearchOutlined /></template>
            </a-input>
            <a-select 
              v-model:value="statusFilter" 
              placeholder="状态筛选" 
              style="width: 120px" 
              allow-clear
            >
              <a-select-option value="completed">已完成</a-select-option>
              <a-select-option value="processing">处理中</a-select-option>
              <a-select-option value="failed">失败</a-select-option>
              <a-select-option value="pending">等待中</a-select-option>
            </a-select>
          </div>
        </div>

        <a-table
          :loading="loading"
          :columns="columns"
          :data-source="filteredTasks"
          row-key="id"
          :pagination="state.pagination"
          @change="onChange"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'id'">
              <span class="task-id">{{ record.id }}</span>
            </template>
            
            <template v-if="column.key === 'status'">
              <a-tag :color="getStatusColor(record.status)">
                <template #icon>
                  <component :is="getStatusIcon(record.status)" :spin="record.status === 'processing'" />
                </template>
                {{ getStatusText(record.status) }}
              </a-tag>
            </template>

            <template v-if="column.key === 'confidence_score'">
              <template v-if="record.confidence_score !== null">
                <a-progress 
                  :percent="Math.round(record.confidence_score * 100)" 
                  size="small" 
                  :status="record.confidence_score >= 0.9 ? 'success' : (record.confidence_score >= 0.7 ? 'normal' : 'exception')"
                />
              </template>
              <span v-else class="text-gray">-</span>
            </template>

            <template v-if="column.key === 'created_at'">
              {{ formatDate(record.created_at) }}
            </template>

            <template v-if="column.key === 'action'">
              <a-button type="link" size="small">查看详情</a-button>
            </template>
          </template>
        </a-table>
      </a-card>
    </div>

    <a-modal 
      v-model:open="createOpen" 
      title="创建OCR任务" 
      @ok="onCreate"
      :confirmLoading="loading"
      width="500px"
    >
      <div class="modal-form">
        <div class="form-item">
          <div class="label">上传图片</div>
          <a-upload
            v-model:file-list="fileList"
            :before-upload="() => false"
            :max-count="1"
            list-type="picture-card"
            class="upload-box"
          >
            <div v-if="fileList.length < 1">
              <plus-outlined />
              <div style="margin-top: 8px">点击上传</div>
            </div>
          </a-upload>
        </div>
        
        <div class="form-item">
          <div class="label">选择模板（可选）</div>
          <a-select 
            v-model:value="templateId" 
            style="width: 100%" 
            allow-clear 
            placeholder="请选择识别模板"
          >
            <a-select-option v-for="item in templates" :key="item.id" :value="item.id">
              {{ item.template_name }}
            </a-select-option>
          </a-select>
          <div class="helper-text">如果不选择模板，系统将尝试自动匹配</div>
        </div>
      </div>
    </a-modal>
  </div>
</template>

<style scoped lang="less">
.page-container {
  padding: 24px;
  background-color: #f0f2f5;
  min-height: 100vh;

  .page-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 24px;

    .header-title {
      h1 {
        font-size: 24px;
        font-weight: 600;
        color: #1a1a1a;
        margin-bottom: 8px;
      }
      .header-subtitle {
        color: #666;
        font-size: 14px;
      }
    }

    .header-actions {
      display: flex;
      gap: 12px;
    }
  }

  .content-wrapper {
    .main-card {
      border-radius: 8px;
      box-shadow: 0 1px 2px rgba(0, 0, 0, 0.03);

      .table-toolbar {
        margin-bottom: 16px;
        display: flex;
        justify-content: space-between;
        align-items: center;

        .filters {
          display: flex;
          gap: 12px;
        }
      }
    }
  }
}

.task-id {
  font-family: monospace;
  color: #1890ff;
}

.text-gray {
  color: #ccc;
}

.modal-form {
  padding: 12px 0;
  
  .form-item {
    margin-bottom: 24px;
    
    .label {
      font-weight: 500;
      margin-bottom: 8px;
      color: #333;
    }
    
    .helper-text {
      font-size: 12px;
      color: #999;
      margin-top: 4px;
    }
  }
}
</style>

// admin-frontend/src/pages/OCRTaskManager.tsx
import React, { useEffect, useState } from 'react';
import { Table, Button, Card, Tag, Modal, Upload, Select, message, Space, Drawer, Descriptions, List } from 'antd';
import { PlusOutlined, UploadOutlined, EyeOutlined, SyncOutlined } from '@ant-design/icons';
import axios from 'axios';
import { apiUrl } from '../lib/api';
import dayjs from 'dayjs';

const { Option } = Select;

interface OCRTask {
  id: string;
  status: string;
  image_url: string;
  template_id: string;
  confidence_score: number;
  created_at: string;
}

const OCRTaskManager: React.FC = () => {
  const [tasks, setTasks] = useState<OCRTask[]>([]);
  const [loading, setLoading] = useState(false);
  const [createModalOpen, setCreateModalOpen] = useState(false);
  const [file, setFile] = useState<any>(null);
  const [templates, setTemplates] = useState<any[]>([]);
  const [selectedTemplate, setSelectedTemplate] = useState<string | undefined>();
  
  // Results Drawer
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [currentTask, setCurrentTask] = useState<OCRTask | null>(null);
  const [results, setResults] = useState<any>(null);
  const [resultsLoading, setResultsLoading] = useState(false);

  useEffect(() => {
    fetchTasks();
    fetchTemplates();
  }, []);

  const fetchTasks = async () => {
    setLoading(true);
    try {
      const res = await axios.get(apiUrl('/api/ocr/tasks'));
      setTasks(res.data);
    } catch (e) {
      message.error('Failed to load tasks');
    } finally {
      setLoading(false);
    }
  };

  const fetchTemplates = async () => {
    try {
      const res = await axios.get(apiUrl('/api/templates'));
      setTemplates(res.data);
    } catch (e) {
      console.error(e);
    }
  };

  const handleCreate = async () => {
    if (!file) {
      message.error('Please select an image');
      return;
    }
    
    const formData = new FormData();
    formData.append('file', file);
    if (selectedTemplate) {
      formData.append('template_id', selectedTemplate);
    }

    try {
      await axios.post(apiUrl('/api/ocr/tasks'), formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });
      message.success('Task created');
      setCreateModalOpen(false);
      setFile(null);
      fetchTasks();
    } catch (e) {
      message.error('Failed to create task');
    }
  };

  const viewResults = async (task: OCRTask) => {
    setCurrentTask(task);
    setDrawerOpen(true);
    setResultsLoading(true);
    try {
      const res = await axios.get(apiUrl(`/api/ocr/tasks/${task.id}/results`));
      setResults(res.data);
    } catch (e) {
      message.error('Failed to load results');
    } finally {
      setResultsLoading(false);
    }
  };

  const columns = [
    {
      title: 'Task ID',
      dataIndex: 'id',
      key: 'id',
      render: (id: string) => <span style={{ fontFamily: 'monospace' }}>{id.slice(0, 8)}...</span>
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      render: (status: string) => {
        let color = 'default';
        if (status === 'completed') color = 'green';
        if (status === 'processing') color = 'blue';
        if (status === 'failed') color = 'red';
        return <Tag color={color}>{status.toUpperCase()}</Tag>;
      }
    },
    {
      title: 'Template',
      dataIndex: 'template_id',
      key: 'template',
      render: (tid: string) => {
        const t = templates.find(tpl => tpl.id === tid);
        return t ? <Tag color="purple">{t.template_name}</Tag> : (tid ? tid.slice(0,8) : '-');
      }
    },
    {
      title: 'Confidence',
      dataIndex: 'confidence_score',
      key: 'conf',
      render: (score: number) => score ? `${(score * 100).toFixed(1)}%` : '-'
    },
    {
      title: 'Created At',
      dataIndex: 'created_at',
      key: 'created_at',
      render: (d: string) => d ? dayjs(d).format('MM-DD HH:mm') : '-'
    },
    {
      title: 'Action',
      key: 'action',
      render: (_: any, record: OCRTask) => (
        <Space>
          <Button size="small" icon={<EyeOutlined />} onClick={() => viewResults(record)}>View</Button>
        </Space>
      )
    }
  ];

  return (
    <div style={{ padding: 24 }}>
      <Card 
        title="OCR Tasks" 
        extra={
            <Space>
                <Button icon={<SyncOutlined />} onClick={fetchTasks} loading={loading}>Refresh</Button>
                <Button type="primary" icon={<PlusOutlined />} onClick={() => setCreateModalOpen(true)}>New Task</Button>
            </Space>
        }
      >
        <Table 
          columns={columns} 
          dataSource={tasks} 
          rowKey="id" 
          loading={loading}
          pagination={{ pageSize: 10 }}
        />
      </Card>

      <Modal
        title="Create New OCR Task"
        open={createModalOpen}
        onCancel={() => setCreateModalOpen(false)}
        onOk={handleCreate}
      >
        <div style={{ marginBottom: 16 }}>
          <p>Select Image:</p>
          <Upload 
            beforeUpload={(f) => { setFile(f); return false; }} 
            maxCount={1}
            onRemove={() => setFile(null)}
          >
            <Button icon={<UploadOutlined />}>Upload Image</Button>
          </Upload>
        </div>
        <div style={{ marginBottom: 16 }}>
          <p>Select Template (Optional):</p>
          <Select 
            style={{ width: '100%' }} 
            allowClear 
            onChange={setSelectedTemplate}
            placeholder="Auto-detect if empty"
          >
            {templates.map(t => (
              <Option key={t.id} value={t.id}>{t.template_name} ({t.template_code})</Option>
            ))}
          </Select>
        </div>
      </Modal>

      <Drawer
        title="Task Results"
        width={600}
        onClose={() => setDrawerOpen(false)}
        open={drawerOpen}
      >
        {currentTask && (
            <Descriptions column={1} bordered size="small">
                <Descriptions.Item label="ID">{currentTask.id}</Descriptions.Item>
                <Descriptions.Item label="Status">{currentTask.status}</Descriptions.Item>
                <Descriptions.Item label="Confidence">{(currentTask.confidence_score * 100).toFixed(1)}%</Descriptions.Item>
            </Descriptions>
        )}
        <div style={{ marginTop: 24 }}>
            <h3>Structured Data</h3>
            <Table 
                loading={resultsLoading}
                dataSource={results?.structured || []}
                rowKey={(r, i) => i?.toString() || ''}
                pagination={false}
                size="small"
                columns={[
                    { title: 'Day', dataIndex: 'weekday', width: 60 },
                    { title: 'Time', render: (_, r: any) => `${r.start_time || ''}-${r.end_time || ''}` },
                    { title: 'Course', dataIndex: 'course' },
                    { title: 'Teacher', dataIndex: 'teacher' },
                    { title: 'Style', dataIndex: 'style' },
                ]}
            />
        </div>
        <div style={{ marginTop: 24 }}>
            <h3>Raw JSON</h3>
            <pre style={{ background: '#f5f5f5', padding: 8, overflow: 'auto', maxHeight: 300 }}>
                {JSON.stringify(results?.raw, null, 2)}
            </pre>
        </div>
      </Drawer>
    </div>
  );
};

export default OCRTaskManager;
